ardera/flutter-pi

src/flutter-pi.c, src/jsmn.h, src/methodchannel.c, src/methodchannel.h, src/platformchannel.c, src/platformchannel.h, src/pluginregistry.c, src/pluginregistry.h, src/services-plugin.c, src/services-plugin.h, src/testplugin.c, src/testplugin.h
- plugin registry featuring hardcoded plugins
- platform channels now support all of the following: String-, Binary-, StandardMessage-, StandardMethod-, JSONMessage- & JSONMethod-codec, including StandardMethodCodec & JSONMethodCodec responses and sending and receiving "not implemented" messages.
- testplugin for testing the functionality of StandardMethod- & JSONMethodCodec.
- helper functions for handling StdMsgCodec- & JSONMsgCodecValues
- ServicesPlugin for handling some service messages, but this is just a stub right now.
=> plugin registry, completely reworked platform channels, test plugin

src/flutter-pi.c
- rename aot cmdline flag to release
- check if flutter engine supports the runtime mode the user chose via cmdline
- let the flutter engine load the AOT data, instead of dlopen/dlsym
=> updates for 1.20

Makefile, include/flutter-pi.h, include/modesetting.h, src/compositor.c, src/flutter-pi.c, src/modesetting.c, src/platformchannel.c, src/plugins/gpiod.c
- fixes #86 
- fixes `Error handling platform message.` on startup
=> fix some issues

include/compositor.h, include/modesetting.h, src/compositor.c, src/flutter-pi.c, src/modesetting.c
This is pretty ugly right now, and I'm not sure the performance is as good as with atomic modesetting
=> reimplement legacy modesetting

README.md
Append slash at the end of flutter_assets to sync the contents without
the flutter_assets directory itself, to the target directory.
Ref: #110
=> Fix rsync instructions in README.md

src/flutter-pi.c
=> fix libinput segfault

src/flutter-pi.c
There's a bunch of places where tabs are used instead of spaces. I've no idea if it's intentional, but I noticed that in the help screen, it causes one paragraph to be overly indented on systems that use tab stops at 8 characters instead of 4, so I'm guessing it's not intentional.
This just replaces all tabs with four spaces uniformly.
Let me know if the better fix is just to change the help string but leave the others.
=> Convert tabs to spaces.

CMakeLists.txt, include/collection.h, include/flutter-pi.h, include/keyboard.h, include/user_input.h, src/flutter-pi.c, src/keyboard.c, src/plugins/text_input.c, src/user_input.c
- somewhat separate user input into an extra module
- better keyboard config loading (better error messages, falls back to default config if possible)
- libinput reports some devices as mouse devices, even though they aren't
- to work around that, only consider a device a mouse device when it has actually send a mouse event
- resolves #118
=> improve input handling

.github/workflows/cmake.yml
This commit fixes the apt-get install command in the GitHub Action (in "install dependencies"): `apt` is not meant to be used in scripts (`apt-get` is ok for scripts), also the missing `-y` means that packages are not installed if they're missing from the system.
=> Fix apt-get (deps) command in GitHub Action

include/locales.h, src/flutter-pi.c, src/locales.c
Subj 
This PR corrects extraction of locale information 
Originally code would include delimiter inside country code, encoding or modifier. 
This PR intentionally excludes these delimiters now, making flutter-pi to initialize flutter locale information without them correctly  
I also added printing of locale during startup, it would be helpful to identify it for user instead of debugging :)
P.s. This only affects applications that rely on system locale information (e.g. easy_localization which uses system locale as default)
=> Correct locale extraction to exclude delims

src/plugins/text_input.c
On standard flutter, no input filtering is done based on the
keyboardType parameter of the TextField constructor.
Input filtering should be done via the inputFormatters parameter of the
TextField constructor. See https://api.flutter.dev/flutter/services/TextInputFormatter-class.html
=> Do not filter text field input based on selected keyboard type.

src/flutter-pi.c
Fix for issue [269](https://github.com/ardera/flutter-pi/issues/269).
gbm_surface_create_with_modifiers is not available for Mali drivers (RockPi 4 RK3399)
=> Fallback to gbm_surface_create if gbm_surface_create_with_modifiers does not work

.github/workflows/cmake.yml, CMakeLists.txt, include/plugins/audioplayers.h, src/plugins/audioplayers/player.c, src/plugins/audioplayers/plugin.c
This a bit update implementation that we used in our machines.
I have a bit of concern on how dispose is supposed to work, but otherwise it is complete
It unites video and audio into single option as both depend on gstreamer
CC @laynor
=> Add gstreamer based audioplayers plugin

CMakeLists.txt, include/filesystem_layout.h, include/flutter-pi.h, src/filesystem_layout.c, src/flutter-pi.c, src/plugins/omxplayer_video_player.c
Allows configuring the filesystem layout of the flutter artifacts, so where flutter-pi looks for the flutter engine, icudtl.dat, asset bundle, etc.
Adds a build flag for using the meta-flutter layout:
```bash
$ cmake ... -DFILESYSTEM_LAYOUT=meta-flutter ...
```
Implements #278.
=> meta-flutter filesystem layout

include/pixel_format.h, src/flutter-pi.c
The base canvas can seldom be transparent and require alpha. To make this tool more compatible with contemporary hardware, make base canvas XR24 pixel format, i.e. without alpha . Fix the --pixelformat parameter handling in the process too.
=> Use XR24 pixel format for base canvas

src/platformchannel.c
These uses of offset 'j' should follow the range check.
=> Fix offset used before range check

src/platformchannel.c
If the while condition ((j < a->size) && _keyInBAlsoInA[j]) fails with j == a->size, then the array access b->keys[j] will be out of bounds.
=> Fix array index out of bounds

README.md
- flutter-pi tool was just published at https://pub.dev/packages/flutterpi_tool.
- update the instructions to use the flutterpi tool for building the app
- still leave the old method in a `<details>` tag
- engine-binaries no longer need to be installed on the target
=> Update instructions to use flutterpi-tool

src/plugins/audioplayers/player.c, src/plugins/audioplayers/plugin.c
As I used my own fork all this time I didn't notice that during preparations of PR I renamed `playerId` into `player-id` when querying variables from channel 😢 
Reference:
https://github.com/bluefireteam/audioplayers/blob/51ab6b4a1271c0da635c3cc8fdb475a542018427/packages/audioplayers_linux/linux/audioplayers_linux_plugin.cc#L106
=> audioplayers: Rename player-id to playerId as it should be

src/egl_gbm_render_surface.c, src/modesetting.c, src/modesetting.h, src/pixel_format.h
Implement uploading multi-planar framebuffers. Mutli-planar framebuffers can arise from normal RGB pixel formats when using modifiers (on Intel, the second plane is used as a Color-Control-Surface for framebuffer compression for example)
- fixes #355
=> fix multiplanar framebuffers

src/egl_gbm_render_surface.c
Only the first locked_fbs' is_locked was initialized.
=> egl_gbm_render_surface: fix initialization of is_locked

src/egl_gbm_render_surface.c
In 869fa7fcfbeb, we added a fallback to be able to create an EGL sruface when the driver do not support modifiers, like the llvmpipe software renderer (or like some proprietary drivers, like the MALI ones), as reported in #269 [0].
However, in c6537673c9b6, there was a big overhaul of renderer infrastructure. That commit lost the with-modifiers code path and only kept the without-modifiers fallback one (i.e. it only kept the call to gbm_surface_create(), not to gbm_surface_create_with_modifiers()).
Then in b0d09f5032a4, the with-modifier code path was re-instated, but in a way that made it exclusive with the without-modifiers one. That is, the without-modifiers code path was not a fallback to when the other failed.
Re-instate the fallback mechanism as initially implemented.
[0] …
=> src/egl_gbm_render_surface: properly fallback to surface with no modifier

src/plugins/gstreamer_video_player/player.c
Docs say it shouldn't make a difference, though in #370 it was reported
to resolve a memory leak on iMX6.
=> video player: Transition to READY before NULL

src/plugins/text_input.c, src/plugins/text_input.h
This patch allows the use of TextInputControl based virtual onscreen keyboards.
see also: https://github.com/flutter/flutter/pull/83974
=> Add TextInputType.none

README.md
I have removed the '$' in the code segments so that you can use the copy function for the installation. Currently the '$' is also copied, which leads to an error message when pasting into the command line.
=> removed '$' from code segments to improve usability

README.md, src/flutter-pi.c, src/util/geometry.h, src/window.c, src/window.h
Enabled running flutter apps without a display attached.
=> dummy display

src/flutter-pi.c
I am not sure whether this is correct because I have only skimmed the code, but assigning the message fixed the gstreamer-video-player camera in release mode for me.
=> fix: assign message to platform message
